name: Generate dist files

on: [push]

jobs:
  gen_dist_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            VSHS.ts
            src/assets/examples/
            deno.json
            package.json
            tsconfig.json