name: Generate dist files

on: [push]

jobs:
  gen_dist_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          overwrite: true
          path: |
            VSHS.ts
            src/assets/examples/
            brython(1).js
            deno.json
            package.json
            tsconfig.json
      - name: upload dist artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist
          asset_name: dist
          asset_content_type: application/gzip
